# Generated by Django 3.0.4 on 2020-03-12 19:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('user_id', models.UUIDField(default=uuid.UUID('56180bc4-4de9-4a56-b8d9-19364e31c707'), editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.UUIDField(default=uuid.UUID('b1925841-b6e9-4e69-9625-4ad22e269825'), editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('toilet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('image', models.FilePathField(null=True, path=None)),
                ('description', models.CharField(max_length=200)),
                ('accesibility', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Provider')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Costumer')),
            ],
        ),
    ]
