# Generated by Django 3.0.4 on 2020-03-12 23:07

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('user_id', models.UUIDField(default=uuid.UUID('63fb5b2c-928d-4bf2-b9f5-a8c6bfa09f02'), editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('toilet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('image_1', models.ImageField(null=True, upload_to='img/')),
                ('image_2', models.ImageField(null=True, upload_to='img/')),
                ('image_3', models.ImageField(null=True, upload_to='img/')),
                ('description', models.CharField(max_length=200, null=True)),
                ('accesibility', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('provider_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Provider')),
            ],
        ),
    ]
