# Generated by Django 3.0.3 on 2020-03-03 22:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('c89468b2-2d37-45c5-9d8b-126bb50f20b1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_id',
            field=models.UUIDField(default=uuid.UUID('505306a5-9d99-4430-8837-1114dbd69971'), editable=False, primary_key=True, serialize=False),
        ),
    ]
