# Generated by Django 3.0.4 on 2020-03-12 23:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('0823a757-ee01-402d-bf54-f1428fb2dee4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
