# Generated by Django 3.0.4 on 2020-03-12 19:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200312_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('9c5d4c6e-905f-4277-88f5-39d895dceb1e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_id',
            field=models.UUIDField(default=uuid.UUID('0616af50-1c15-4c5b-9270-37daf2c7da30'), editable=False, primary_key=True, serialize=False),
        ),
    ]
