# Generated by Django 3.0.4 on 2020-03-12 19:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200312_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('59210278-bb56-4775-9c78-63f32ccb6c28'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_id',
            field=models.UUIDField(default=uuid.UUID('ba0d2799-93d2-40e7-9a22-31fbfa81a822'), editable=False, primary_key=True, serialize=False),
        ),
    ]
