# Generated by Django 3.0.3 on 2020-03-03 23:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200303_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('9a0d89ca-ecbc-402d-822f-645a0c18602a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_id',
            field=models.UUIDField(default=uuid.UUID('782c5fdb-bcc5-4916-8b2a-fc3c428da966'), editable=False, primary_key=True, serialize=False),
        ),
    ]
