# Generated by Django 3.0.4 on 2020-03-12 23:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200312_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('cbb59976-f972-4b89-87cd-75802dfec013'), editable=False, primary_key=True, serialize=False),
        ),
    ]
