# Generated by Django 3.0.3 on 2020-03-03 23:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200303_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('dbfa9453-b654-40c3-9508-62c999bcbc55'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_id',
            field=models.UUIDField(default=uuid.UUID('0b4c38ab-3456-4776-a2c4-288db8bbddaf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
