# Generated by Django 3.0.4 on 2020-03-12 19:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200312_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('83ef2cf6-beb2-4b49-ad26-07fc9cc36617'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_id',
            field=models.UUIDField(default=uuid.UUID('1960ff3c-c983-4868-8e1b-e1109f07fedc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
