# Generated by Django 3.0.3 on 2020-03-03 23:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200303_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('1927110f-4b64-4795-b244-de537e81c0d1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_id',
            field=models.UUIDField(default=uuid.UUID('b74e6f4e-47fe-46c5-ae85-a1a6e574ee6c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
