# Generated by Django 3.0.3 on 2020-03-04 00:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200303_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('43d55353-b95d-4c98-92a2-217e9390547f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_id',
            field=models.UUIDField(default=uuid.UUID('85d198e5-c261-4407-9e20-87a269da433f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
