# Generated by Django 3.0.4 on 2020-03-12 19:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200312_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('646d81f9-26bb-4f11-a993-55831ab74551'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_id',
            field=models.UUIDField(default=uuid.UUID('f534487d-3482-4686-b6fe-ac887fbe1ec9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
