# Generated by Django 3.0.4 on 2020-03-12 23:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200312_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('1fbe4a8e-53e6-4bf5-a62a-9eaf2c729371'), editable=False, primary_key=True, serialize=False),
        ),
    ]
