# Generated by Django 3.0.4 on 2020-03-12 19:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200312_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('f28a7232-0e44-4fb6-8dca-fcb2c78b4672'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_id',
            field=models.UUIDField(default=uuid.UUID('3eb1881f-49ba-467d-8867-4d8ec130e4f0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
