# Generated by Django 3.0.4 on 2020-03-12 23:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200312_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('c95191f2-b61f-400f-9c3e-1171512b6c65'), editable=False, primary_key=True, serialize=False),
        ),
    ]
