# Generated by Django 3.0.4 on 2020-03-12 19:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200312_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('43c67b46-3963-4d44-a62c-aadf93434f5f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_id',
            field=models.UUIDField(default=uuid.UUID('997f2e80-684b-46fc-ad87-4204ea40b62d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
