# Generated by Django 3.0.4 on 2020-03-12 19:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200312_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('f3cfd2a1-4af6-4836-b20b-28f8baf159f0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_id',
            field=models.UUIDField(default=uuid.UUID('7106202f-4979-4a58-8ea4-0535c3ac1be5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
