# Generated by Django 3.0.4 on 2020-03-12 19:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20200312_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('63d2e2f4-b384-4e85-9732-d92c4b823048'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_id',
            field=models.UUIDField(default=uuid.UUID('ffca497c-0089-42f2-bdda-c6edc3fa26c7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
