# Generated by Django 3.0.4 on 2020-03-12 19:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20200312_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('6468625c-29ae-43a5-a84f-ea741ce4f039'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_id',
            field=models.UUIDField(default=uuid.UUID('25f4c50d-9169-4e82-bcc0-06fb5969c2ae'), editable=False, primary_key=True, serialize=False),
        ),
    ]
